# This is a basic workflow to help you get started with Actions
name: Releases

# Controls when the workflow will run
on: 
  push:
  # Triggers the workflow on push or pull request events but only for the tagged
    tags:
    - '*'
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  web:
    name: Web build
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "3.3.10"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter build web --release
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./build/web/
  # This workflow contains a single job called "build"
  apk-linux:
    name: APK & linux build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.3.10"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Release APK
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          asset_name: money_manager.apk
          tag: ${{ github.ref }}
          overwrite: true
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev -y
      - run: flutter build linux --release
      - name: Compress linux directory
        run: tar cfzv build/linux/x64/release/money_manager_linux_x64.tar.xz ./build/linux/x64/release/bundle
      - uses: actions/upload-artifact@v3
        with:
          name: linux-release
          path: build/linux/x64/release/money_manager_linux_x64.tar.xz
      - name: Release Linux
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/linux/x64/release/money_manager_linux_x64.tar.xz
          asset_name: money_manager_linux_x64.tar.xz
          tag: ${{ github.ref }}
          overwrite: true
  windows:
    name: Windows build
    runs-on: windows-latest
    env:
      FLUTTER_VERSION: "3.3.10"
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter build windows --release
      - name: Compress
        run: tar.exe -a -c -f build/windows/runner/money_manager_windows_x64.zip build/windows/runner/Release
      - uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: build/windows/runner/money_manager_windows_x64.zip
      - name: Release Windows
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/windows/runner/money_manager_windows_x64.zip
          asset_name: money_manager_windows_x64.zip
          tag: ${{ github.ref }}
          overwrite: true
      